name: integration-test-gradle
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 16
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run integration test with gradle
        working-directory: "integration"
        run: ../gradlew test
